volumes:
  db-data:
  yarn:
  nm-app:
  nm-admin:
  pw-deps:
  minio-data:


services:
  mc:
    image: minio/mc
    depends_on:
      - minio
    restart: "no"
    environment: &minioenv
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
    entrypoint: /app/scripts/local/minio-bootstrap.sh
    volumes:
      - .:/app
  app:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: [ "yarn", "watch" ]
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    ports:
      - "1337:1337" # for the app itself
      - "8888:8888" # for viewing webpack-bundle-analyzer
      - "8080:8080" # for serving test coverage html
    depends_on:
      - db
      - redis
      - minio
    environment:
      <<: *minioenv
      APP_HOSTNAME: http://localhost:1337
      DOMAIN: localhost:1337
      FEATURE_FILE_STORAGE_SERVICE: 'true'
      FEATURE_LOCAL_BUILD_REPORTS: 'active'
      FEATURE_LOCAL_S3_ENDPOINT: 'true'
      NODE_ENV: development
      PORT: 1337
      PRODUCT: pages
      UAA_HOST: http://localhost:9001
      UAA_HOST_DOCKER_URL: http://uaa:8080
      USER_AUDITOR: federalist
      CLOUD_FOUNDRY_API_HOST: ${CLOUD_FOUNDRY_API_HOST}
      CLOUD_FOUNDRY_OAUTH_TOKEN_URL: ${CLOUD_FOUNDRY_API_HOST}/oauth/token
      CF_API_USERNAME: deploy_user
      CF_API_PASSWORD: deploy_pass
      PAGES_EDITOR_HOST: https://editor.example.gov
      PROXY_DOMAIN: localhost:1337
      QUEUES_BUILD_TASKS_CONCURRENCY: 1
      OPS_EMAIL: ops@example.gov
  bull-board:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: [ "scripts/wait-for-it.sh", "redis:6379", "--", "yarn", "start-bull-board:local" ]
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    ports:
      - "1340:1340"
    depends_on:
      - redis
    environment:
      ADMIN_GITHUB_ORGANIZATION: FederalistLocal
      ADMIN_GITHUB_TEAM: federalist-local-admins
      APP_ENV: local
      APP_HOSTNAME: http://localhost:1340
      PORT: 1340
      PRODUCT: pages
      REDIS_URL: redis://redis:6379
      SESSION_SECRET: bull-board
      UAA_CLIENT_ID: pages-client
      UAA_CLIENT_SECRET: client-secret
      UAA_HOST_DOCKER_URL: http://uaa:8080
      UAA_LOGIN_HOST: http://localhost:9001
  admin-client:
    build:
      dockerfile: ./admin-client/Dockerfile-admin
      context: .
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - ./admin-client:/app
      - nm-admin:/app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - app
    command: [ "yarn", "dev" ]
    environment:
      API_URL: http://localhost:1337
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # expose db on host at port 5433
    environment:
      POSTGRES_DB: federalist
      POSTGRES_TEST_DB: federalist-test
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
  echo:
    image: node:20.9-bullseye
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    environment:
      HOST: 0.0.0.0
      PORT: 8989
    command: node app/scripts/echo.js
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9100:9000"
      - "9101:9001"
    command: 'server --console-address=":9001" /data'
    environment:
      <<: *minioenv
    volumes:
      - minio-data:/data
      - .:/app
  mock-cf-api:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: [ "yarn", "mock-cf-api" ]
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
    ports:
      - "3456:3456"
    environment:
      <<: *minioenv
