version: '3'

services:
  app:
    image: node:ci
    volumes:
      - ../..:/opt/concourse-ci/task/app
    depends_on:
      - db
      - redis
    environment:
      YARN_VERSION: 0.24.6-1
      CC_TEST_REPORTER_ID: 101a439651b6abd27e5440028a53b5b8f08fe0889f3948d5f58f6cf9f7c786a0
      CONCOURSE: 'true'
      APP_HOSTNAME: http://localhost:1337
      PRODUCT: pages
      CLOUD_FOUNDRY_API_HOST: https://api.example.com
      CLOUD_FOUNDRY_OAUTH_TOKEN_URL: https://api.example.com/oauth/token
      CF_API_USERNAME: deploy_user
      CF_API_PASSWORD: deploy_pass
      PROXY_DOMAIN: localhost:1337
      CI: true
      FEATURE_FILE_STORAGE_SERVICE: true
      PAGES_EDITOR_HOST: https://editor.example.gov
      OPS_EMAIL: ops@example.gov
  db:
    image: postgres:ci
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:ci
